# Generated by Django 4.2.16 on 2026-06-04 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('lycee', 'Lycée'), ('superieur', 'Supérieur'), ('professionnel', 'Professionnel')], default='lycee', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('coefficient', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
